version: '2'
services:
    uninet-app:
        image: uninet
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://uninet-mysql:3306/uninet?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=uninet-elasticsearch:9300
        ports:
            - 8080:8080
    uninet-mysql:
        extends:
            file: mysql.yml
            service: uninet-mysql
    uninet-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: uninet-elasticsearch
